BlobStorageAuthentication.WebApp/Controllers/UploadWithADController.cs
using Azure.Identity;
using Azure.Storage.Blobs;
using BlobStorageAuthentication.WebApp.Auth;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Web;
using System.Text;

namespace BlobStorageAuthentication.WebApp.Controllers
{
    public class UploadWithADController : Controller
    {
        public UserAcquisitionTokenCredential UserAcquisitionTokenCredential { get; }

        public UploadWithADController(UserAcquisitionTokenCredential userAcquisitionTokenCredential)
        {
            UserAcquisitionTokenCredential = userAcquisitionTokenCredential;
        }
        // GET: UploadWithADController
        public ActionResult Index()
        {
            return View();
        }

        // GET: UploadWithADController/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        //    POST: UploadWithADController/Create
        [AuthorizeForScopes(Scopes = new string[]
             { "https://storage.azure.com/user_impersonation" })]
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(IFormFile file) 
        {
            try
            {
                var user = HttpContext.User;
                var blobContent = new StringBuilder();
                using StreamReader reader= new StreamReader(file.OpenReadStream());
                while (!reader.EndOfStream) blobContent.AppendLine(reader.ReadLine());
                string containerName = "adauthcontainer";
                string blobEndpoint = "https://anishstrgdemo1.blob.core.windows.net/adauthcontainer";
                Uri blobUri = new Uri(blobEndpoint);

                BlobServiceClient blobServiceClient = new BlobServiceClient(blobUri, UserAcquisitionTokenCredential);
                BlobContainerClient container = blobServiceClient.GetBlobContainerClient(containerName);

                var result = await container.UploadBlobAsync(file.FileName, new MemoryStream(Encoding.UTF8.GetBytes(blobContent.ToString())));

                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: UploadWithADController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: UploadWithADController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UploadWithADController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: UploadWithADController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BlobStorageAuthentication.WebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace BlobStorageAuthentication.WebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

BlobStorageAuthentication.WebApp/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AspNetCoreAzureStorage.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

BlobStorageAuthentication.WebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BlobStorageAuthentication.WebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

BlobStorageAuthentication.WebApp/Pages/Index.cshtml
@page
@using AspNetCoreAzureStorage.Pages
@model IndexModel
@{
    ViewData["Title"] = "Azure Storage and ASP.NET Core";
}


<div class="card">
    <div class="card-header">Azure Storage and ASP.NET Core</div>

    <div class="card-body">
        <p>ASP.NET Core </p>
        <p>Azure AD</p>
        <p>Azure Storage</p>
        <p>Microsoft SQL</p>

    </div>
</div>

BlobStorageAuthentication.WebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlobStorageAuthentication.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlobStorageAuthentication.WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">BlobStorageAuthentication.WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UploadWithAD" asp-action="Create">Upload</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BlobStorageAuthentication.WebApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BlobStorageAuthentication.WebApp/Views/UploadWithAD/Create.cshtml
@page
@{
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
 
<!DOCTYPE html>
 
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <form method="post" asp-route="UploadWithAD/Create" enctype="multipart/form-data">
    <input type="file" name="file" /> 
    <button type="submit">Upload File</button>
</form>
</body>
</html>